# GitHub Pages Deployment for Anchored Web Application
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build and deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build web application
        run: |
          # Create build directory
          mkdir -p dist
          
          # Copy web application files to build directory
          cp -r web-app/* dist/
          
          # Ensure HTTPS is enforced in production
          echo "Configuring for HTTPS deployment..."
          
          # Create .nojekyll file to prevent Jekyll processing
          touch dist/.nojekyll
          
          # Ensure CNAME file is present for custom domain
          echo "anchored.site" > dist/CNAME
          
          # Create robots.txt for SEO
          cat > dist/robots.txt << EOF
          User-agent: *
          Allow: /
          
          Sitemap: https://anchored.site/sitemap.xml
          EOF
          
          # Create basic sitemap.xml
          cat > dist/sitemap.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://anchored.site/</loc>
              <lastmod>$(date -u +%Y-%m-%d)</lastmod>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
            <url>
              <loc>https://anchored.site/dashboard.html</loc>
              <lastmod>$(date -u +%Y-%m-%d)</lastmod>
              <changefreq>daily</changefreq>
              <priority>0.8</priority>
            </url>
            <url>
              <loc>https://anchored.site/account.html</loc>
              <lastmod>$(date -u +%Y-%m-%d)</lastmod>
              <changefreq>monthly</changefreq>
              <priority>0.6</priority>
            </url>
          </urlset>
          EOF
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: anchored.site